import swaggerAutogen from 'swagger-autogen';

const outputFile = './src/routes/swagger-output.json';
//const endpointsFiles = ['./src/routes/livrosRoutes.js', './src/routes/autoresRoutes.js'];
const endpointsFiles = ['./src/routes/index.js'];

const doc = {
  info: {
      version: "1.0.0",
      title: "My API",
      description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  servers: [
    {
      url: "http://localhost:3000/",
      description: "Local - Node"
    },
    {
      url: "http://localhost:5000/",
      description: "Local - Heroku"
    },
    {
      url: "https://infinite-depths-15472.herokuapp.com/",
      description: "Deploy - Heroku"
    }
  ],

//   host: "localhost:5000",
//   basePath: "/",
//  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
      {
          "name": "User",
          "description": "Endpoints"
      }
  ]
}
// swaggerAutogen(outputFile, endpointsFiles);

// swaggerAutogen(outputFile, endpointsFiles);

// swaggerAutogen()(outputFile, endpointsFiles, doc);
swaggerAutogen({openapi: '3.0.0'})(outputFile, endpointsFiles, doc).then(async () => {
     console.log('Iniciando swagger!');
     await import('./server.js'); 
  });


// swaggerAutogen(outputFile, endpointsFiles).then(async () => {
//   console.log('Iniciando swagger!');
//   await import('./server.js'); // Your project's root file
// });

